FROM python:3.13-bookworm

RUN apt-get update
RUN apt-get install -y tidy

WORKDIR /workspace

RUN /bin/bash -c "echo \"export PATH=\$PATH:/root/.local/bin/\" >> /root/.bashrc"

COPY pyproject.toml .
RUN pip3 install --user -e .[allbuild,dev,staticpipesdev]

CMD ["bash"]
