name: Lint
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: 3.13
        architecture: x64
    - run: pip install -e .[allbuild,dev,staticpipesdev]
    - run: black --check .
    - run: isort --check .
    - run: flake8
    - run: mypy --install-types --non-interactive -p staticpipes
